#!/usr/bin/env python

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
a = b = 1
finalSum = 0
while b < 4000000:
	
	a,b = b ,a + b
	if not b % 2:
		finalSum += b

print 'The sum of the even-valued terms in Fibonacci sequence below 4000000 is', finalSum #4613732

